# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the action will run. Triggers the workflow on push new tag.
on:
  push:
    tags: 
      - v*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checkout master branch
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          ref: master

      # Setup .npmrc file to publish to npm
      - name: Setup Node with the right version
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      # Install dependencies
      - run: yarn install --frozen-lockfile

      # Run lint
      - name: Run lint test
        run: yarn run lint

      # Clear last build cache
      - name: Clear last build cache
        run: yarn run clear-build-cache

      # Build
      - name: Build
        run: yarn run build

      # Publish to NPM
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
